version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqla-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "TuPasswordSeguro123!"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql/data
      - ./db-scripts:/scripts
    entrypoint: /bin/bash /scripts/entrypoint.sh

  backend:
    build: ./sqla-backend
    container_name: sqla-backend
    ports:
      - "3000:3000"
    environment:
      DB_USER: "sa"
      DB_PASSWORD: "TuPasswordSeguro123!"
      DB_SERVER: "sql-server"
      DB_DATABASE: "master" # O la base de datos por defecto de tu aplicación
      DB_PORT: "1433"
    depends_on:
      - sql-server

  frontend:
    build: ./sqla-app
    container_name: sqla-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  sql-data:
